export const Occupations: string[] = [
  'Advocacia',
  'Saúde',
  'Design',
  'Tecnologia',
  'Logística',
  'Coach',
  'Educação',
  'Engenharia',
  'Finanças',
  'Gastronomia',
  'Marketing',
  'Recursos Humanos',
  'Serviços Domésticos',
  'Artes',
  'Entretenimento',
  'Turismo',
  'Esportes',
  'Beleza e Estética',
  'Consultoria',
  'Jornalismo',
  'Psicologia',
  'Veterinária',
  'Agricultura',
  'Moda',
  'Música',
  'Fotografia',
  'Cinema e TV',
  'Arquitetura',
  'Administração',
];
